# Generated by Django 5.2.4 on 2025-07-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cropcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='machinery',
            options={'ordering': ['name']},
        ),
    ]
